jenkins:
  systemMessage: "Test Naxus\n\n"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: admin
tool:
  git:
    installations:
    - home: "git"
      name: "Default"

jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/juanmatomas07/te.git' }
                        branch '*/master'
                        extensions {}
                    }
                  }
              }
          }
      }

credentials:
   system:
     domainCredentials:
       - credentials:
           - usernamePassword:
               scope:    GLOBAL
               id:       github-user
               username: juanmatomas07
               password: 096436664jm
